services:
  postgres:
    image: postgres:latest
    container_name: BigDataSnowflake
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-big-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./исходные данные:/init_data
volumes:
  postgres-big-data: